name: AUR Synchronization

on:
    release:
        types: [published]

jobs:
    aur-sync:
        runs-on: ubuntu-latest
        steps:
          - name: Get repo description
            id: repo
            uses: actions/github-script@v7.0.1
            with:
                script: |
                    const repo = await github.rest.repos.get({
                        owner: context.repo.owner,
                        repo: context.repo.repo
                    });
                    core.setOutput("description", repo.data.description);
          - uses: Blaadworks/AurSynchronization@v1.0.0
            with:
                pkg_name: blaadpapers
                pkg_desc: ${{ steps.repo.outputs.description }}
                ssh_key: ${{ secrets.SSH_KEY_AUR }}
