name: AUR Synchronization
on:
    release:
        types: [published]
    workflow_dispatch:
jobs:
    aur-sync:
        runs-on: ubuntu-latest
        steps:
        -   name: Get Repository Data
            id: repo
            uses: actions/github-script@v7.0.1
            with:
                script: |
                    const { description, license } = (await github.rest.repos.get(context.repo)).data;

                    core.setOutput("description", description);
                    core.setOutput("license", license.spdx_id);
        -   uses: Blaadworks/AurSynchronization@v1.1.0
            with:
                ssh_key: ${{ secrets.SSH_KEY_AUR }}
                pkg_name: blaadpapers
                pkg_desc: ${{ steps.repo.outputs.description }}
                pkg_license: ${{ steps.repo.outputs.license }}
